Feature/add tests
OpenSourcePolitics/decidim-spam_detection pull request #1
Opened 2021-11-25 21:44 UTC by armandfardeau

2021-11-26 14:29 UTC, paulinebessoles approved these changes

2021-11-29 11:34 UTC, Quentinchampenois requested changes
Nice work! 
Just a light suggestion

2021-11-29 11:34 UTC, Quentinchampenois commented on app/services/decidim/spam_detection/mark_users_service.rb
> +          email: "spam_detection_bot@opensourcepolitcs.eu",
This email could have been defined with environment variable

2021-11-29 15:22 UTC, Quentinchampenois approved these changes

2021-11-29 16:03 UTC, merged